site_name: Agentic Security
repo_url: https://github.com/msoedov/agentic_security
site_url: https://msoedov.github.io/agentic_security
site_description: Open-source LLM Vulnerability Scanner for safe and reliable AI.
site_author: Agentic Security Team
edit_uri: edit/main/docs/
repo_name: msoedov/agentic_security
copyright: Maintained by <a href="https://msoedov.github.io">Agentic Security Team</a>.

nav:
  - Home: index.md
  - Features: probe_data.md
  - Core Concepts:
    - Probe Actor: probe_actor.md
    - Refusal Actor: refusal_classifier_plugins.md
    - Agent Spec: http_spec.md
  - Setup:
    - Installation: installation.md
    - Getting Started: getting_started.md
    - Configuration: configuration.md
  - Advanced Topics:
    - Dataset Extension: datasets.md
    - External Modules: external_module.md
    - CI/CD Integration: ci_cd.md
    - Bayesian Optimization: optimizer.md
    - Image Generation: image_generation.md
  - Reference:
    - API Reference: api_reference.md
  - Community:
    - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [agentic_security]


footer:
  links: []  # Removes the default footer credits

theme:
  name: material
  features:
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  favicon: "https://res.cloudinary.com/dq0w2rtm9/image/upload/v1737555066/r17hrkre246doczwmvbv.png"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/msoedov/agentic_security
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/agentic_security

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
